apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.image.name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/camunda$ /camunda/app/ permanent;
      rewrite ^/camunda/$ /camunda/app/ permanent;
      rewrite ^/camunda/app$ /camunda/app/ permanent;
    nginx.ingress.kubernetes.io/rewrite-target: /camunda/$2
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: lims-tls
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.image.name }}-service
          servicePort: 8080
        path: /camunda(/|$)(.*)
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.image.name }}-ingress-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: lims-tls
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.image.name }}-service
          servicePort: 8080
        path: /camunda-api(/|$)(.*)