apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.name }}-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: {{ .Values.image.name }}
